### PR TITLE
Ignore unknown post types

### LINKED ISSUE #1: Cannot parse XML: Unknown variant `wpcode`, expected `attachment` or `post`
Hi, while running your code, I get the following error:

    thread 'main' panicked at 'cannot parse xml: Error(Custom("unknown variant `wpcode`, expected `attachment` or `post`"), State { next_error: None, backtrace: Some(stack backtrace:
<details>
  <summary>Click here to see full backtrace</summary>

```
   0: error_chain::make_backtrace::h5b686804ab41ada6 (0x102109d5b)
   1: <error_chain::State as core::default::Default>::default::h09c5eb318dfad097 (0x102109db3)
   2: serde_xml_rs::error::Error::from_kind::h7a478809b1f443b4 (0x1020d2e43)
   3: <serde_xml_rs::error::Error as core::convert::From<serde_xml_rs::error::ErrorKind>>::from::hfc0c139747f5a2ab (0x1020d2ed3)
   4: <T as core::convert::Into<U>>::into::h2f5704076fa26591 (0x102091383)
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/convert/mod.rs:542
   5: <serde_xml_rs::error::Error as serde::de::Error>::custom::hbd9540c6456aabff (0x1020913cf)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/error.rs:75
   6: serde::de::Error::unknown_variant::h3ad77eff32dfa7a3 (0x10232e87f)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:246
   7: <wordpress_to_zola::_IMPL_DESERIALIZE_FOR_PostType::<impl serde::de::Deserialize for wordpress_to_zola::PostType>::deserialize::__FieldVisitor as serde::de::Visitor>::visit_str::hd9b9d52754eee793 (0x102096be7)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:143
   8: <serde::de::value::StrDeserializer<E> as serde::de::Deserializer>::deserialize_any::h7cace7046d559870 (0x10209a433)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/value.rs:381
   9: <serde::de::value::StrDeserializer<E> as serde::de::Deserializer>::deserialize_identifier::h95f3dc464bf5ba15 (0x10209a4fb)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/macros.rs:134
  10: <wordpress_to_zola::_IMPL_DESERIALIZE_FOR_PostType::<impl serde::de::Deserialize for wordpress_to_zola::PostType>::deserialize::__Field as serde::de::Deserialize>::deserialize::hda3aadf62906a651 (0x102096c83)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:143
  11: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::hb01ea840792232cd (0x1020b49fb)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:779
  12: <serde_xml_rs::de::var::EnumAccess<R> as serde::de::EnumAccess>::variant_seed::hc866fc6d191e9b01 (0x1020a34db)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/var.rs:33
  13: serde::de::EnumAccess::variant::h8e472d9c8249db11 (0x1020a2dc7)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:1976
  14: <wordpress_to_zola::_IMPL_DESERIALIZE_FOR_PostType::<impl serde::de::Deserialize for wordpress_to_zola::PostType>::deserialize::__Visitor as serde::de::Visitor>::visit_enum::hbd7281ae917da568 (0x102096eaf)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:143
  15: <&mut serde_xml_rs::de::Deserializer<R> as serde::de::Deserializer>::deserialize_enum::{{closure}}::hb71451fbe779bab5 (0x10209c927)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:284
  16: serde_xml_rs::de::Deserializer<R>::read_inner_value::he4fcbaf681de99eb (0x10209ac97)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:145
  17: <&mut serde_xml_rs::de::Deserializer<R> as serde::de::Deserializer>::deserialize_enum::h1c3c3b3b8e28355e (0x10209c833)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:284
  18: wordpress_to_zola::_IMPL_DESERIALIZE_FOR_PostType::<impl serde::de::Deserialize for wordpress_to_zola::PostType>::deserialize::h5e4bfa08a4f5fca3 (0x102096ac3)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:143
  19: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::h72e42d002c005550 (0x1020b486b)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:779
  20: <serde_xml_rs::de::map::MapAccess<R> as serde::de::MapAccess>::next_value_seed::h6697fef5920969ba (0x10209341b)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/map.rs:62
  21: serde::de::MapAccess::next_value::hc02f0e28758334c8 (0x10209167b)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:1840
  22: <wordpress_to_zola::_IMPL_DESERIALIZE_FOR_Item::<impl serde::de::Deserialize for wordpress_to_zola::Item>::deserialize::__Visitor as serde::de::Visitor>::visit_map::hb50fb3ebf51a29ea (0x1020963a7)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:122
  23: <&mut serde_xml_rs::de::Deserializer<R> as serde::de::Deserializer>::deserialize_struct::h956a1285af4710a9 (0x10209dffb)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:210
  24: wordpress_to_zola::_IMPL_DESERIALIZE_FOR_Item::<impl serde::de::Deserialize for wordpress_to_zola::Item>::deserialize::hb984bb2170b59350 (0x102095543)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:122
  25: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::hee3b0bb9aa383845 (0x1020b4aaf)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:779
  26: <serde_xml_rs::de::seq::SeqAccess<R> as serde::de::SeqAccess>::next_element_seed::hff7c1336d0b1d86a (0x10209956f)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/seq.rs:61
  27: serde::de::SeqAccess::next_element::h9dbb29923946a5ae (0x102098edb)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:1701
  28: <serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::VecVisitor<T> as serde::de::Visitor>::visit_seq::h6aef270da2c39dce (0x1020b380b)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/impls.rs:864
  29: <&mut serde_xml_rs::de::Deserializer<R> as serde::de::Deserializer>::deserialize_seq::hb514b6f69c34967b (0x10209c7cf)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:302
  30: serde::de::impls::<impl serde::de::Deserialize for alloc::vec::Vec<T>>::deserialize::h4bd05925c79ce7b7 (0x1020986af)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/impls.rs:875
  31: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::h80beed818db1d023 (0x1020b488f)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:779
  32: <serde_xml_rs::de::map::MapAccess<R> as serde::de::MapAccess>::next_value_seed::hb115f01960013793 (0x102093693)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/map.rs:62
  33: serde::de::MapAccess::next_value::h09b3fdcf59b761ba (0x1020915eb)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:1840
  34: <wordpress_to_zola::_IMPL_DESERIALIZE_FOR_Channel::<impl serde::de::Deserialize for wordpress_to_zola::Channel>::deserialize::__Visitor as serde::de::Visitor>::visit_map::h960358fff491efd7 (0x1020951c3)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:115
  35: <&mut serde_xml_rs::de::Deserializer<R> as serde::de::Deserializer>::deserialize_struct::h8d214019fc77a5be (0x10209d947)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:210
  36: wordpress_to_zola::_IMPL_DESERIALIZE_FOR_Channel::<impl serde::de::Deserialize for wordpress_to_zola::Channel>::deserialize::hc3e9a83fac52ae84 (0x102094c0f)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:115
  37: <core::marker::PhantomData<T> as serde::de::DeserializeSeed>::deserialize::h8ef065999761d76c (0x1020b496b)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:779
  38: <serde_xml_rs::de::map::MapAccess<R> as serde::de::MapAccess>::next_value_seed::h072679edce724dea (0x102092a17)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/map.rs:62
  39: serde::de::MapAccess::next_value::h18ee7989ceaa4967 (0x10209160f)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.89/src/de/mod.rs:1840
  40: <wordpress_to_zola::_IMPL_DESERIALIZE_FOR_Rss::<impl serde::de::Deserialize for wordpress_to_zola::Rss>::deserialize::__Visitor as serde::de::Visitor>::visit_map::h81617b149e8f3e59 (0x10209498b)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:109
  41: <&mut serde_xml_rs::de::Deserializer<R> as serde::de::Deserializer>::deserialize_struct::h5fdfedd67ab6aaae (0x10209d293)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:210
  42: wordpress_to_zola::_IMPL_DESERIALIZE_FOR_Rss::<impl serde::de::Deserialize for wordpress_to_zola::Rss>::deserialize::hda7c8b56f7066fb6 (0x10209455f)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:109
  43: serde_xml_rs::de::from_reader::hda653c9a46d26c06 (0x10209a843)
             at /Users/nat/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-xml-rs-0.3.1/src/de/mod.rs:60
  44: wordpress_to_zola::convert::h67271810dbeedecf (0x1020a3c67)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:62
  45: wordpress_to_zola::main::hb1ac1477d099e035 (0x1020a3a67)
             at /Users/nat/Downloads/wordpress-to-zola/src/main.rs:51
  46: core::ops::function::FnOnce::call_once::h9eb95538869e55c0 (0x1020a961b)
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227
  47: std::sys_common::backtrace::__rust_begin_short_backtrace::h55396d90d75fc8ee (0x102099a2f)
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:123
  48: std::rt::lang_start::{{closure}}::hc2e3e94c3552365d (0x1020b546b)
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:145
  49: std::rt::lang_start_internal::h35c587f98e9244f6 (0x10231179f)
  50: std::rt::lang_start::h84e916c477e018d9 (0x1020b5437)
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:144
  51: _main (0x1020a57fb)) })', src/main.rs:62:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
   2: core::result::unwrap_failed
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
   3: core::result::Result<T,E>::expect
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1255:23
   4: wordpress_to_zola::convert
             at ./src/main.rs:62:20
   5: wordpress_to_zola::main
             at ./src/main.rs:51:9
   6: core::ops::function::FnOnce::call_once
             at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

I suspect some plugin is adding some custom entry which is not understood. My guess is this plugin here: https://wordpress.org/plugins/insert-headers-and-footers/

### PR DESCRIPTION
**Pull request by andybalaam**
Fixes #1 

Includes a potential way to test some of this stuff, and some formatting changes that you can feel free to ask me to remove :-)

### CODE REVIEW

**Comment by TatriX** [comment]
Hi!
Thanks for the contribution!

Why ignore `Cargo.lock`?

**Comment by andybalaam** [comment]
> Why ignore `Cargo.lock`?

It was removed in https://github.com/TatriX/wordpress-to-zola/pull/2 so I assumed we didn't want it stored in git.

Personally I would normally prefer to include it. Very happy to re-add it in a separate PR (to merge before this one) if you like.

**Comment by TatriX** [comment]
Oh, right, I missed that. Shall we just re-add it in this PR?

**Comment by andybalaam** [comment]
I made a [separate PR](https://github.com/TatriX/wordpress-to-zola/pull/4) and rebased this one on top of that - hope it was helpful.

**Comment by TatriX** [comment]
Thank you for the PR!
As you may imagine I'm not actively *using* this tool, so I hope things are still working for people :)

**Comment by andybalaam** [comment]
> As you may imagine I'm not actively _using_ this tool

Yep, migration tools have the weird property :-)

It's working well for me, and I have a number of changes I am making to my version, some of which will become PRs for you to consider.

**Comment by andybalaam** [comment]
Thank you for writing it!

**Pull request merged**
